from github.abc.actor import Actor as Actor
from github.abc.assignable import Assignable as Assignable
from github.abc.closable import Closable as Closable
from github.abc.comment import Comment as Comment
from github.abc.commentable import Commentable as Commentable
from github.abc.deletable import Deletable as Deletable
from github.abc.gitobject import GitObject as GitObject
from github.abc.gitsignature import GitSignature as GitSignature
from github.abc.labelable import Labelable as Labelable
from github.abc.lockable import Lockable as Lockable
from github.abc.memberstatusable import MemberStatusable as MemberStatusable
from github.abc.minimizable import Minimizable as Minimizable
from github.abc.node import Node as Node
from github.abc.packageowner import PackageOwner as PackageOwner
from github.abc.participable import Participable as Participable
from github.abc.profileowner import ProfileOwner as ProfileOwner
from github.abc.projectowner import ProjectOwner as ProjectOwner
from github.abc.reactable import Reactable as Reactable
from github.abc.repositorynode import RepositoryNode as RepositoryNode
from github.abc.repositoryowner import RepositoryOwner as RepositoryOwner
from github.abc.sponsorable import Sponsorable as Sponsorable
from github.abc.starrable import Starrable as Starrable
from github.abc.subscribable import Subscribable as Subscribable
from github.abc.type import Type as Type
from github.abc.uniformresourcelocatable import UniformResourceLocatable as UniformResourceLocatable
from github.abc.updatable import Updatable as Updatable
