class Actor:
    @property
    def avatar_url(self) -> str: ...
    @property
    def login(self) -> str: ...

    async def fetch_avatar_url(self, *, size: int=...) -> str: ...
    async def fetch_login(self) -> str: ...
