from typing import Optional, Union

from datetime import datetime

from github.iterator import CollectionIterator
from github.enums import CommentAuthorAssociation
from github.objects import Bot
from github.objects import CommentContentEdit
from github.objects import User


class Comment():
    @property
    def author_association(self) -> CommentAuthorAssociation: ...
    @property
    def body(self) -> str: ...
    @property
    def body_html(self) -> str: ...
    @property
    def body_text(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...
    @property
    def edited_at(self) -> Optional[datetime]: ...
    @property
    def is_email_response(self) -> bool: ...
    @property
    def published_at(self) -> datetime: ...
    @property
    def updated_at(self) -> datetime: ...
    @property
    def viewer_is_author(self) -> bool: ...

    async def fetch_author(self) -> Union[Bot, User]: ...
    async def fetch_editor(self) -> Union[Bot, User]: ...

    def fetch_edits(self, **kwargs) -> CollectionIterator[CommentContentEdit]: ...
