from github.objects import Repository


class GitObject():
    @property
    def commit_resource_path(self) -> str: ...
    @property
    def commit_url(self) -> str: ...
    @property
    def oid(self) -> str: ...
    @property
    def oid_abbreviated(self) -> str: ...

    async def fetch_repository(self) -> Repository: ...
