from typing import List

from github.objects import Label


class Labelable():
    async def fetch_labels(self) -> List[Label]: ...
    async def add_labels(self, *labels: Label) -> None: ...
    async def clear_labels(self) -> None: ...
    async def remove_labels(self, *labels: Label) -> None: ...
