from typing import List

from github.iterator import CollectionIterator
from github.objects import Label


class Labelable():
    def fetch_labels(self, **kwargs) -> CollectionIterator: ...

    async def add_labels(self, *labels: Label) -> None: ...
    async def clear_labels(self) -> None: ...
    async def remove_labels(self, *labels: Label) -> None: ...
