from typing import Optional


class ProfileOwner():
    @property
    def has_pinnable_items(self) -> bool: ...
    @property
    def location(self) -> Optional[str]: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def pinned_items_remaining(self) -> int: ...
    @property
    def viewer_can_change_pinned_items(self) -> bool: ...
    @property
    def website(self) -> Optional[str]: ...

    async def fetch_email(self) -> Optional[str]: ...
