from typing import Optional

from github.objects import SponsorshipListing


class Sponsorable():
    @property
    def has_sponsorship_listing(self) -> bool: ...
    @property
    def is_sponsoring_viewer(self) -> bool: ...
    @property
    def viewer_can_sponsor(self) -> bool: ...
    @property
    def viewer_is_sponsoring(self) -> bool: ...

    async def fetch_sponsorship_listing(self) -> Optional[SponsorshipListing]: ...
