import aiohttp
import graphql

from github.content import CodeOfConduct, License
from github.metadata import Metadata, RateLimit
from github.repository import Topic


class Client(graphql.client.Client):
    def __init__(self, token: str, *, session: aiohttp.ClientSession, user_agent: str=...) -> None: ...

    async def fetch_all_codes_of_conduct(self, **kwargs) -> list[CodeOfConduct]: ...
    async def fetch_all_licenses(self, **kwargs) -> list[License]: ...
    async def fetch_code_of_conduct(self, key: str, **kwargs) -> CodeOfConduct: ...
    async def fetch_license(self, key: str, **kwargs) -> License: ...
    async def fetch_metadata(self, **kwargs) -> Metadata: ...
    async def fetch_rate_limit(self, **kwargs) -> RateLimit: ...
    async def fetch_topic(self, name: str, **kwargs) -> Topic: ...
