import graphql


class GitHubError(graphql.client.ClientError): pass
class ClientResponseError(graphql.client.ClientResponseError, GitHubError): pass
class ClientResponseHTTPError(graphql.client.ClientResponseHTTPError, ClientResponseError): pass
class ClientResponseHTTPUnauthorizedError(ClientResponseHTTPError): pass
class ClientResponseGraphQLError(graphql.client.ClientResponseGraphQLError, ClientResponseError): pass
class ClientResponseGraphQLForbiddenError(ClientResponseGraphQLError): pass
class ClientResponseGraphQLInternalError(ClientResponseGraphQLError): pass
class ClientResponseGraphQLNotFoundError(ClientResponseGraphQLError): pass
class ClientResponseGraphQLUnprocessableError(ClientResponseGraphQLError): pass
