from typing import List, Optional

from github.abc import Node
from github.abc import Type
from .licenserule import LicenseRule


class License(Node, Type):
    @property
    def body(self) -> str: ...
    @property
    def conditions(self) -> List[LicenseRule]: ...
    @property
    def description(self) -> str: ...
    @property
    def implementation(self) -> str: ...
    @property
    def is_featured(self) -> bool: ...
    @property
    def is_hidden(self) -> bool: ...
    @property
    def is_pseudo(self) -> bool: ...
    @property
    def key(self) -> str: ...
    @property
    def limitations(self) -> List[LicenseRule]: ...
    @property
    def name(self) -> str: ...
    @property
    def nickname(self) -> Optional[str]: ...
    @property
    def permissions(self) -> List[LicenseRule]: ...
    @property
    def spdx_id(self) -> str: ...
    @property
    def url(self) -> str: ...
