from github.abc import Actor
from github.abc import Node
from github.abc import ProfileOwner
from github.abc import ProjectOwner
from github.abc import RepositoryOwner
from github.abc import Sponsorable
from github.abc import Type
from github.abc import UniformResourceLocatable


class Organization(Actor, Node, ProfileOwner, ProjectOwner, RepositoryOwner,
                   Sponsorable, Type, UniformResourceLocatable):
    @property
    def database_id(self) -> int: ...
    @property
    def description(self) -> str: ...
    @property
    def is_verified(self) -> bool: ...
    @property
    def new_team_resource_path(self) -> str: ...
    @property
    def new_team_url(self) -> str: ...
    @property
    def teams_resource_path(self) -> str: ...
    @property
    def teams_url(self) -> str: ...
    @property
    def viewer_can_administer(self) -> bool: ...
    @property
    def viewer_can_create_repositories(self) -> bool: ...
    @property
    def viewer_can_create_teams(self) -> bool: ...
    @property
    def viewer_is_member(self) -> bool: ...
