from github.interfaces import Type


class Metadata(Type):
    @property
    def git_ip_addresses(self) -> list[str]: ...
    @property
    def github_services_sha(self) -> str: ...
    @property
    def hook_ip_addresses(self) -> list[str]: ...
    @property
    def importer_ip_addresses(self) -> list[str]: ...
    @property
    def is_password_authentication_verifiable(self) -> bool: ...
    @property
    def pages_ip_addresses(self) -> list[str]: ...
