name: Deploy

on:
  push:
  release:
    types: [ released ]

jobs:
  job:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DOCS_REPOSITORY: ${{ github.repository_owner }}/docs
      DOCS_DIRECTORY: ./docs/${{ github.event.repository.name }}
      DOCS_DIRECTORY_LATEST_NAME: dotcom
      PYTHON_VERSION: 3.9

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v2
      with:
        path: ${{ github.event.repository.name }}

    - name: Checkout ${{ env.DOCS_REPOSITORY }}
      uses: actions/checkout@v2
      with:
        path: docs
        repository: ${{ env.DOCS_REPOSITORY }}
        token: ${{ secrets.DOCS_TOKEN }}

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install
      working-directory: ./${{ github.event.repository.name }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade .[docs]

    - name: Build
      if: ${{ github.event_name == 'push' }}
      run: |
        if [ -d ${{ env.DOCS_DIRECTORY }}/${{ env.DOCS_DIRECTORY_LATEST_NAME }} ]; then rm -r ${{ env.DOCS_DIRECTORY }}/${{ env.DOCS_DIRECTORY_LATEST_NAME }}; fi
        python -m sphinx -b dirhtml -a -E -n -T -W --keep-going ./${{ github.event.repository.name }}/docs ${{ env.DOCS_DIRECTORY }}/${{ env.DOCS_DIRECTORY_LATEST_NAME }}

    - name: Build
      if: ${{ github.event_name == 'release' }}
      run: |
        if [ -d ${{ env.DOCS_DIRECTORY }}/${{ github.event.release.tag_name }} ]; then rm -r ${{ env.DOCS_DIRECTORY }}/${{ github.event.release.tag_name }}; fi
        python -m sphinx -b dirhtml -a -E -n -T -W --keep-going ./${{ github.event.repository.name }}/docs ${{ env.DOCS_DIRECTORY }}/${{ github.event.release.tag_name }}
        cd ${{ env.DOCS_DIRECTORY }}
        if [ -d ${{ env.DOCS_DIRECTORY }}/stable ]; then rm -r ${{ env.DOCS_DIRECTORY }}/stable; fi
        cp -r ${{ github.event.release.tag_name }} stable

    - name: Push
      continue-on-error: true
      working-directory: docs
      run: |
        git config user.name ShineyDev
        git config user.email 30989490+ShineyDev@users.noreply.github.com
        git add .
        git commit -m "update docs to ${{ github.repository }}@${{ github.sha }}"
        git push
