name: Deploy

on: [ pull_request, push ]

jobs:
  job:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ShineyDev/github
      uses: actions/checkout@v2
      with:
        path: github

    - name: Checkout ShineyDev/docs
      uses: actions/checkout@v2
      with:
        path: docs
        repository: ShineyDev/docs
        token: ${{ secrets.DOCS_TOKEN }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install
      working-directory: ./github
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade .[docs]

    - name: Build
      if: ${{ github.event_name == 'push' }}
      env:
        OUTPUT_DIRECTORY: ./docs/${{ github.event.repository.name }}/latest
      run: |
        if [ -d ${{ env.OUTPUT_DIRECTORY }} ]; then rm -r ${{ env.OUTPUT_DIRECTORY }}; fi
        python -m sphinx -b dirhtml -a -E -n -T -W --keep-going ./${{ github.event.repository.name }}/docs ${{ env.OUTPUT_DIRECTORY }}
        cd ${{ env.OUTPUT_DIRECTORY }}
        rm -r .doctrees
        rm -r _sources
        rm .buildinfo

    - name: Build
      if: ${{ github.event_name == 'pull_request' }}
      env:
        OUTPUT_DIRECTORY: ./docs/${{ github.event.repository.name }}/pull/${{ github.event.pull_request.number }}
      run: |
        if [ -d ${{ env.OUTPUT_DIRECTORY }} ]; then rm -r ${{ env.OUTPUT_DIRECTORY }}; fi
        python -m sphinx -h dirhtml -a -E -n -T -W --keep-going ./${{ github.event.repository.name }}/docs ${{ env.OUTPUT_DIRECTORY }}
        cd ${{ env.OUTPUT_DIRECTORY }}
        rm -r .doctrees
        rm -r _sources
        rm .buildinfo

    - name: Push
      if: ${{ github.event_name == 'push' }}
      continue-on-error: true
      working-directory: ./docs
      run: |
        git config user.name ShineyDev
        git config user.email 30989490+ShineyDev@users.noreply.github.com
        git add .
        git commit -m "update docs for ${{ github.repository }}@${{ github.sha }}"
        git push

    - name: Push
      if: ${{ github.event_name =='pull_request' }}
      continue-on-error: true
      working-directory: ./docs
      run: |
        git config user.name ShineyDev
        git config user.email 30989490+ShineyDev@users.noreply.github.com
        git add .
        git commit -m "create docs for ${{ github.repository }}#{{ github.event.pull_request.number }}@${{ github.sha }}"
        git push

    - name: Comment
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            ...context.repo,
            body: `Hey there! I'm a robot.\nI've built the [documentation for this pull request](https://shineydev.github.io/docs/${context.repo.name}/pull/${context.payload.pull_request.number}) for you.`,
            issue_number: context.payload.pull_request.number
          }))
