name: Lint

on:
  pull_request:
  push:
  workflow_dispatch:

env:
  AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  job:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Lint
      uses: github/super-linter/slim@v4
      env:
        GITHUB_TOKEN: ${{ env.AUTH_TOKEN }}
        VALIDATE_PYTHON_BLACK: true
        VALIDATE_YAML: true
