name: Lint

on:
  pull_request:
  push:
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12

jobs:
  black:
    name: Lint (black)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel

    - name: Install black
      run: |-
        python -m pip install --upgrade black

    - name: Lint (black)
      run: python -m black --check --diff .  # TODO: ShineyDev/black-action

  yaml:
    name: Lint (yaml)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel

    - name: Install yamllint
      run: |-
        python -m pip install --upgrade yamllint

    - name: Lint (yamllint)
      run: python -m yamllint -c .github/linters/yamllint.yml -f github .
